language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - extra
    - android-23
    - build-tools-23.0.2
before_install:
  openssl aes-256-cbc -K $encrypted_41e5df756875_key -iv $encrypted_41e5df756875_iv -in app/google-services.json.enc -out app/google-services.json -d
script: ./gradlew clean clone build
